#!/bin/bash

# Tested against flyctl v0.0.456

set -e

cookie="$1"

if [ -z "$cookie" ] ||\
    [ "$cookie" = "help" ] ||\
    [ "$cookie" = "-h" ] ||\
    [ "$cookie" = "--help" ]; then
    echo 'Usage: script/observer <cookie>

Note that you must have a WireGuard tunnel established.

See https://fly.io/docs/reference/private-networking/#private-network-vpn'
    exit 1
fi

# Get the first IPv6 address returned
ip_array=( $(fly ips private | awk '(NR>1){ print $3 }') )
IP=${ip_array[0]}

# Get the Fly app name. Assumes it is used as part of the full node name
APP_NAME=`fly status --json | jq '.Name' -r`
FULL_NODE_NAME="${APP_NAME}@${IP}"
echo Attempting to connect to $FULL_NODE_NAME

# Export the BEAM settings for running the "iex" command.
# This creates a local node named "my_remote". The name used isn't important.
# The cookie must match the cookie used in your project so the two nodes can connect.
iex --erl "-proto_dist inet6_tcp" --sname my_remote --cookie "$cookie" -e "IO.inspect(Node.connect(:'${FULL_NODE_NAME}'), label: \"Node Connected?\"); IO.inspect(Node.list(), label: \"Connected Nodes\"); :observer.start"
