#!/bin/bash

set -e

module_name=$1
otp_app_name=$2

if [ -z "$module_name" ]; then
  echo "Usage: <module_name> <otp_app_name>"
  exit 1
fi

if [ -z "$otp_app_name" ]; then
  echo "Usage: $module_name <otp_app_name>"
  exit 1
fi

# Replace my_foo with $otp_app_name in all file or directory names.
find . -depth -name "*phoenix_template*" -execdir bash -c 'mv "$1" "${1//phoenix_template/$2}"' bash {} $otp_app_name \;