#!/bin/bash

set -e

module_name=$1
otp_app_name=$2

if [ -z "$module_name" ]; then
  echo "Usage: <module_name> <otp_app_name>"
  exit 1
fi

if [ -z "$otp_app_name" ]; then
  echo "Usage: $module_name <otp_app_name>"
  exit 1
fi

# Replace phx_app_template with $otp_app_name in all file or directory names.
find . -depth -name "*phx_app_template*" -execdir bash -c 'mv "$1" "${1//phx_app_template/$2}"' bash {} $otp_app_name \;

# Replace PhxAppTemplate with $module_name in all file contents.
find . -type f \
  -not -path "./.git/*" \
  -not -path "./deps/*" \
  -not -path "./_build/*" \
  -not -path "./.elixir_ls/*" \
  -not -path "./script/*" \
  -not -path "./priv/static/*" \
  -not -path "./assets/node_modules/*" \
  -exec sed -i '' -e "s/PhxAppTemplate/$module_name/g" {} \;

# Replace phx_app_template with $otp_app_name in all file contents.
find . -type f \
  -not -path "./.git/*" \
  -not -path "./deps/*" \
  -not -path "./_build/*" \
  -not -path "./.elixir_ls/*" \
  -not -path "./script/*" \
  -not -path "./priv/static/*" \
  -not -path "./assets/node_modules/*" \
  -exec sed -i '' -e "s/phx_app_template/$otp_app_name/g" {} \;