#!/bin/bash

set -e

module_name=$1
phoenix_template_name=$2

if [ -z "$module_name" ]; then
  echo "Usage: <module_name> <phoenix_template_name>"
  exit 1
fi

if [ -z "$phoenix_template_name" ]; then
  echo "Usage: $module_name <phoenix_template_name>"
  exit 1
fi