name: CI & Deploy

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env: { MIX_ENV: test }
    timeout-minutes: 10

    services:
      db:
        image: postgres:15
        env: { POSTGRES_PASSWORD: postgres }
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - uses: erlef/setup-beam@v1
        with: { otp-version: 26.0.2, elixir-version: 1.15.4 }
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: test
  #   timeout-minutes: 10
  #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
  #   environment:
  #     name: production
  #     url: https://example.invalid
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: superfly/flyctl-actions/setup-flyctl@67ddda2a87628f1aff28a54b8a708879ec62c80f
  #     - run: flyctl deploy --remote-only
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
